server:
  port: 8088
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 20
        min-idle: 5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/low-code?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 233031
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.pdx.entity
  configuration:
    map-underscore-to-camel-case: true
